spring.application.name=currency-calculator

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/currency_calculator}
spring.datasource.username=${DB_USERNAME:currency_dev}
spring.datasource.password=${DB_PASSWORD:currency_dev}
spring.jpa.hibernate.ddl-auto=update
