spring.application.name=currency-calculator

spring.datasource.url=jdbc:postgresql://localhost:5432/currency_calculator
spring.datasource.username=${DB_USERNAME:currency}
spring.datasource.password=${DB_PASSWORD:currency_dev}
spring.jpa.hibernate.ddl-auto=update
